POST https://node-do-zero-x94w.onrender.com/videos
Content-Type: application/json

{
    "title": "video node",
    "description": "Esse é o terceiro vídeo",
    "duration": 180
}

###

GET https://node-do-zero-x94w.onrender.com/videos

###

GET https://node-do-zero-x94w.onrender.com/videos?search=node

###

PUT https://node-do-zero-x94w.onrender.com/videos/2ef802eb-b001-4760-963a-09d9d984868d
Content-Type: application/json

{
    "title": "video js",
    "description": "Esse é o primeiro vídeo",
    "duration": 180
}

###

DELETE https://node-do-zero-x94w.onrender.com/videos/15f144dd-23ef-4c73-8fd3-a3eced3c61b2